In [15]:
import pandas as pd
from ast import literal_eval
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import warnings; warnings.simplefilter('ignore')

In [16]:
data=pd.read_csv("tmdb_5000_movies.csv")
data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [17]:
data=data.drop(['homepage','production_companies','production_countries','status'],axis=1)
data.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,release_date,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",John Carter,6.1,2124

In [18]:
data.columns

Index(['budget', 'genres', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'release_date', 'revenue',
       'runtime', 'spoken_languages', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [19]:
data['genres'] = data['genres'].fillna('[]').apply(literal_eval)
data['tagline']=data['tagline'].fillna('')
data['desc']=data['overview']+data['tagline']
data['desc']=data['desc'].fillna('')

In [20]:
data=data.sort_values('vote_average',ascending=False)

In [21]:
data.head(10)

,budget,genres,id,keywords,original_language,original_title,overview,popularity,release_date,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count,desc
3519,0,"[{'id': 35, 'name': 'Comedy'}]",89861,"[{""id"": 131, ""name"": ""italy""}, {""id"": 8250, ""n...",en,Stiff Upper Lips,Stiff Upper Lips is a broad parody of British ...,0.356495,1998-06-12,0,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",,Stiff Upper Lips,10.0,1,Stiff Upper Lips is a broad parody of British ...
4247,1,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",361505,[],en,Me You and Five Bucks,"A womanizing yet lovable loser, Charlie, a wai...",0.094105,2015-07-07,0,90.0,[],"A story about second, second chances",Me You and Five Bucks,10.0,2,"A womanizing yet lovable loser, Charlie, a wai..."
4045,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",78373,"[{""id"": 1415, ""name"": ""small town""}, {""id"": 15...",en,"Dancer, Texas Pop. 81","Four guys, best friends, have grown up togethe...",0.376662,1998-05-01,565592,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",in the middle of nowhere they had everything,"Dancer, Texas Pop. 81",10.0,1,"Four guys, best friends, have grown up togethe..."
4662,0,"[{'id': 35, 'name': 'Comedy'}]",40963,"[{""id"": 10183, ""name"": ""independent film""}]",en,Little Big Top,An aging out of work clown returns to his smal...,0.092100,2006-01-01,0,0.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",,Little Big Top,10.0,1,An aging out of work clown returns to his smal...
3992,0,[],346081,[],en,Sardaarji,A ghost hunter uses bottles to capture trouble...,0.296981,2015-06-26,0,0.0,[],,Sardaarji,9.5,2,A ghost hunter uses bottles to capture trouble...
2386,0,"[{'id': 37, 'name': 'Western'}, {'id': 28, 'na...",69848,"[{""id"": 6091, ""name"": ""war""}, {""id"": 6092, ""na...",en,One Man's Hero,One Man's Hero tells the little-known story of...,0.910529,1999-08-02,0,121.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",One man's hero is another man's traitor.,One Man's Hero,9.3,2,One Man's Hero tells the little-known story of...
2970,10500000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",88641,[],en,There Goes My Baby,A group of high school seniors meets in the su...,0.037073,1994-09-02,123509,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",,There Goes My Baby,8.5,2,A group of high school seniors meets in the su...
1881,25000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",278,"[{""id"": 378, ""name"": ""prison""}, {""id"": 417, ""n...",en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,136.747729,1994-09-23,28341469,142.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Framed in the 1940s for the double murder of h...
2796,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",43867,"[{""id"": 1930, ""name"": ""kidnapping""}, {""id"": 25...",en,The Prisoner of Zenda,An Englishman on a Ruritarian holiday must imp...,4.021389,1937-09-03,0,101.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...",The most thrilling swordfight ever filmed...,The Prisoner of Zenda,8.4,11,An Englishman on a Ruritarian holiday must imp...
3337,6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",238,"[{""id"": 131, ""name"": ""italy""}, {""id"": 699, ""na...",en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,1972-03-14,245066411,175.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",An offer you can't refuse.,The Godfather,8.4,5893,"Spanning the years 1945 to 1955, a chronicle o..."

In [22]:
cv = CountVectorizer(max_features=5000,stop_words='english')
vec = cv.fit_transform(data['desc'])

In [23]:

cos_sim = cosine_similarity(vec)

In [24]:

data = data.reset_index()
indices = pd.Series(data.index, index=data['title'])

In [25]:


def get_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cos_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    movie_indices = [i[0] for i in sim_scores]
    return data.iloc[movie_indices].title

In [26]:
get_recommendations("The Dark Knight").head()

259                       The Dark Knight Rises
4059                             Batman Forever
1649                             Batman Returns
98      Batman: The Dark Knight Returns, Part 2
863                                      Batman
Name: title, dtype: object